### ISSUE TITLE
Issue with the menu items of nav

### ISSUE THREAD

**Issue by realslimshanky** [Cybros/cybros.github.io#22]
After clicking on one of the menu items on `nav`, it doesn't collapse and the user has to manually collapse the `nav`. Preview: https://media.giphy.com/media/l3diPw1GyVg36vz3O/source.mp4

I would like to help out in fixing this issue.

**Comment by punit-agarwal** [comment]
Thanks for pointing the UI error @realslimshanky 
We will be more than happy to merge your pull request if it solves the bug.

**Comment by realslimshanky** [comment]
Thank you, @punit-agarwal will send a PR soon.
